"""create core tables"""

from __future__ import annotations

import sys
from pathlib import Path

from alembic import op
import sqlalchemy as sa

ROOT_DIR = Path(__file__).resolve().parents[2]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from app.db.types import GUID


# revision identifiers, used by Alembic.
revision = '7a030fe0912f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('account',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.Enum('KES', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('type', sa.Enum('USER', 'TREASURY', 'ESCROW', 'EXTERNAL', name='accounttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('available_balance <= balance', name=op.f('ck_account_ck_available_leq_balance')),
    sa.CheckConstraint('available_balance >= 0', name=op.f('ck_account_ck_available_balance_non_negative')),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_account_ck_balance_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_account_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('user_id', 'currency', name='uq_user_currency')
    )
    op.create_table('transaction',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('account_id', GUID(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'TRANSFER', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('KES', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_transaction_account_id_account')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction')),
    sa.UniqueConstraint('reference', name='uq_transaction_reference')
    )
    op.create_index(op.f('ix_transaction_reference'), 'transaction', ['reference'], unique=True)
    op.create_index('ix_transaction_user_account', 'transaction', ['user_id', 'account_id'], unique=False)
    op.create_table('ledgerentry',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('transaction_id', GUID(), nullable=False),
    sa.Column('account_id', GUID(), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='ledgerentrydirection'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_ledgerentry_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_ledgerentry_transaction_id_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledgerentry'))
    )
    op.create_table('transferrequest',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('source_account_id', GUID(), nullable=False),
    sa.Column('destination_account_id', GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('KES', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='requeststatus'), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_account_id'], ['account.id'], name=op.f('fk_transferrequest_destination_account_id_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_account_id'], ['account.id'], name=op.f('fk_transferrequest_source_account_id_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_transferrequest_transaction_id_transaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transferrequest'))
    )
    op.create_index(op.f('ix_transferrequest_request_key'), 'transferrequest', ['request_key'], unique=True)
    op.create_table('withdrawalrequest',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('account_id', GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('KES', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='requeststatus'), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_withdrawalrequest_account_id_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_withdrawalrequest_transaction_id_transaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawalrequest'))
    )
    op.create_index(op.f('ix_withdrawalrequest_request_key'), 'withdrawalrequest', ['request_key'], unique=True)
    op.create_table('idempotencykey',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('recovery_point', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotencykey')),
    sa.UniqueConstraint('request_hash', name=op.f('uq_idempotency_request_hash'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotencykey')
    op.drop_index(op.f('ix_withdrawalrequest_request_key'), table_name='withdrawalrequest')
    op.drop_table('withdrawalrequest')
    op.drop_index(op.f('ix_transferrequest_request_key'), table_name='transferrequest')
    op.drop_table('transferrequest')
    op.drop_table('ledgerentry')
    op.drop_index('ix_transaction_user_account', table_name='transaction')
    op.drop_index(op.f('ix_transaction_reference'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
